#avatar: assets/img/face.jpg

# Build settings
encoding: UTF-8

paginate: 3
paginate_path: "/blog/:num/"
# include: ['.htaccess']
ErrorDocument: 404 /404.html
exclude: [node_modules, gulpfile.js, package.json, Gemfile, Gemfile.lock, test.cmd]
port: 80

sass:
  sass_dir: assets/css
  style: :compacted

markdown: kramdown
plugins: [jekyll-paginate, jekyll-watch, kramdown, coderay, redcarpet, jekyll-tidy]

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input: GFM
  enable_coderay: true
  syntax_highlighter: coderay
  syntax_highlighter_opts: {}


  # coderay:
  #   coderay_wrap:              div
  #   coderay_line_numbers:      inline
  #   coderay_line_number_start: 1
  #   coderay_tab_width:         1
  #   coderay_bold_every:        10
  #   coderay_css:               style
jekyll_tidy:
  #exclude: [index.html]
  compress_html: false
